name: Portfolio_Backend CI/CD

on:
  push:
    branches:
      main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pytest boto3

      - name: Run tests
        run: pytest test_lambda.py

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Package Lambda
        run: zip lambda_function.zip lambda_function.py

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}